
ALTER TABLE holdingsitemscollection ALTER COLUMN complete TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE holdingsitemscollection ALTER COLUMN modified TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE holdingsitemscollection ALTER COLUMN created TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE holdingsitemscollection ALTER COLUMN updated TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE holdingsitemsitem ALTER COLUMN modified TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE holdingsitemsitem ALTER COLUMN created TYPE TIMESTAMP WITH TIME ZONE;
